"""initial migration

Revision ID: d2c2a81eec13
Revises: 
Create Date: 2026-02-04 18:19:38.729301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c2a81eec13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_templates',
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('deployment_steps', sa.JSON(), nullable=False),
    sa.Column('database_required', sa.Boolean(), nullable=False),
    sa.Column('database_type', sa.String(length=50), nullable=True),
    sa.Column('required_inputs', sa.JSON(), nullable=False),
    sa.Column('default_resources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index('ix_templates_active', 'application_templates', ['is_active'], unique=False)
    op.create_index('ix_templates_category', 'application_templates', ['category'], unique=False)
    op.create_table('executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('step_execution_id', sa.UUID(), nullable=True),
    sa.Column('execution_type', sa.String(length=50), nullable=False),
    sa.Column('target_resource_id', sa.UUID(), nullable=True),
    sa.Column('runtime_type', sa.String(length=50), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'QUEUED', 'CLAIMED', 'STARTED', 'COMPLETED', 'FAILED', 'CANCELLED', name='execution_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('deployment_result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('ix_executions_app_state', 'executions', ['application_id', 'state'], unique=False)
    op.create_index(op.f('ix_executions_application_id'), 'executions', ['application_id'], unique=False)
    op.create_index(op.f('ix_executions_lease_expires_at'), 'executions', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_executions_lease_owner'), 'executions', ['lease_owner'], unique=False)
    op.create_index(op.f('ix_executions_priority'), 'executions', ['priority'], unique=False)
    op.create_index('ix_executions_queued_lookup', 'executions', ['state', 'priority', 'created_at'], unique=False, postgresql_where=sa.text("state = 'QUEUED'"))
    op.create_index('ix_executions_recoverable_lookup', 'executions', ['state', 'lease_expires_at'], unique=False, postgresql_where=sa.text("state = 'STARTED'"))
    op.create_index(op.f('ix_executions_started_at'), 'executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_executions_state'), 'executions', ['state'], unique=False)
    op.create_index(op.f('ix_executions_tenant_id'), 'executions', ['tenant_id'], unique=False)
    op.create_index('ix_executions_tenant_state', 'executions', ['tenant_id', 'state'], unique=False)
    op.create_table('infrastructure_nodes',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.Enum('APP_NODE', 'DB_NODE', 'EDGE_NODE', name='nodetype'), nullable=False),
    sa.Column('internal_ip', sa.String(length=50), nullable=False),
    sa.Column('public_ip', sa.String(length=50), nullable=True),
    sa.Column('runtime_agent_url', sa.String(length=500), nullable=False),
    sa.Column('supported_runtimes', sa.JSON(), nullable=False),
    sa.Column('total_cpu', sa.Float(), nullable=False),
    sa.Column('total_memory', sa.Integer(), nullable=False),
    sa.Column('total_storage', sa.Integer(), nullable=False),
    sa.Column('available_cpu', sa.Float(), nullable=False),
    sa.Column('available_memory', sa.Integer(), nullable=False),
    sa.Column('available_storage', sa.Integer(), nullable=False),
    sa.Column('max_containers', sa.Integer(), nullable=False),
    sa.Column('active_containers', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'FULL', 'MAINTENANCE', 'OFFLINE', name='nodestatus'), nullable=False),
    sa.Column('health_status', sa.Enum('HEALTHY', 'UNHEALTHY', 'UNKNOWN', name='nodehealthstatus'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('node_id'),
    sa.UniqueConstraint('node_name')
    )
    op.create_index(op.f('ix_infrastructure_nodes_node_type'), 'infrastructure_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_infrastructure_nodes_status'), 'infrastructure_nodes', ['status'], unique=False)
    op.create_index('ix_nodes_heartbeat', 'infrastructure_nodes', ['last_heartbeat_at'], unique=False)
    op.create_index('ix_nodes_status', 'infrastructure_nodes', ['status'], unique=False)
    op.create_index('ix_nodes_type_status', 'infrastructure_nodes', ['node_type', 'status'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('template_version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_inputs', sa.JSON(), nullable=False),
    sa.Column('current_deployment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATING', 'RUNNING', 'STOPPED', 'FAILED', 'DELETING', 'DELETED', name='applicationstatus'), nullable=False),
    sa.Column('health_status', sa.Enum('UNKNOWN', 'HEALTHY', 'UNHEALTHY', 'STARTING', name='healthstatus'), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('resource_limits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['application_templates.template_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index('ix_applications_tenant_created', 'applications', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_index('ix_applications_tenant_status', 'applications', ['tenant_id', 'status'], unique=False)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('template_version', sa.String(length=50), nullable=False),
    sa.Column('resolved_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DEPLOYING', 'RUNNING', 'FAILED', 'ROLLED_BACK', 'DELETED', name='deploymentstatus'), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('internal_endpoints', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rollback_on_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deployment_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index('ix_deployments_app_created', 'deployments', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_deployments_application_id'), 'deployments', ['application_id'], unique=False)
    op.create_index(op.f('ix_deployments_created_at'), 'deployments', ['created_at'], unique=False)
    op.create_index('ix_deployments_status', 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_deployments_tenant_id'), 'deployments', ['tenant_id'], unique=False)
    op.create_table('domains',
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('is_subdomain', sa.Boolean(), nullable=False),
    sa.Column('parent_domain', sa.String(length=255), nullable=True),
    sa.Column('dns_verified', sa.Boolean(), nullable=False),
    sa.Column('dns_verified_at', sa.DateTime(), nullable=True),
    sa.Column('dns_records', sa.JSON(), nullable=False),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_provider', sa.String(length=50), nullable=False),
    sa.Column('ssl_status', sa.String(length=50), nullable=False),
    sa.Column('ssl_cert_path', sa.String(length=500), nullable=True),
    sa.Column('ssl_cert_expires_at', sa.DateTime(), nullable=True),
    sa.Column('target_deployment_id', sa.UUID(), nullable=True),
    sa.Column('target_port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_index('ix_domains_app', 'domains', ['application_id'], unique=False)
    op.create_index(op.f('ix_domains_application_id'), 'domains', ['application_id'], unique=False)
    op.create_index(op.f('ix_domains_domain_name'), 'domains', ['domain_name'], unique=True)
    op.create_index('ix_domains_tenant', 'domains', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_domains_tenant_id'), 'domains', ['tenant_id'], unique=False)
    op.create_table('provisioned_databases',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.Column('db_user', sa.String(length=255), nullable=False),
    sa.Column('db_password_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('connection_string_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('storage_size_gb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('backup_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('db_name')
    )
    op.create_index(op.f('ix_provisioned_databases_application_id'), 'provisioned_databases', ['application_id'], unique=False)
    op.create_index(op.f('ix_provisioned_databases_tenant_id'), 'provisioned_databases', ['tenant_id'], unique=False)
    op.create_index('ix_provisioned_dbs_app', 'provisioned_databases', ['application_id'], unique=False)
    op.create_index('ix_provisioned_dbs_tenant', 'provisioned_databases', ['tenant_id'], unique=False)
    op.create_index('ix_provisioned_dbs_type', 'provisioned_databases', ['db_type'], unique=False)
    op.create_table('deployed_resources',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('CONTAINER', 'DATABASE', 'VOLUME', 'NETWORK', name='resourcetype'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.deployment_id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['infrastructure_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_deployed_resources_deployment_id'), 'deployed_resources', ['deployment_id'], unique=False)
    op.create_index('ix_resources_deployment', 'deployed_resources', ['deployment_id'], unique=False)
    op.create_index('ix_resources_type', 'deployed_resources', ['resource_type'], unique=False)
    op.create_table('deployment_step_executions',
    sa.Column('step_execution_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.deployment_id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.execution_id'], ),
    sa.PrimaryKeyConstraint('step_execution_id')
    )
    op.create_index(op.f('ix_deployment_step_executions_deployment_id'), 'deployment_step_executions', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_step_executions_status'), 'deployment_step_executions', ['status'], unique=False)
    op.create_index('ix_step_executions_deployment', 'deployment_step_executions', ['deployment_id'], unique=False)
    op.create_index('ix_step_executions_status', 'deployment_step_executions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_step_executions_status', table_name='deployment_step_executions')
    op.drop_index('ix_step_executions_deployment', table_name='deployment_step_executions')
    op.drop_index(op.f('ix_deployment_step_executions_status'), table_name='deployment_step_executions')
    op.drop_index(op.f('ix_deployment_step_executions_deployment_id'), table_name='deployment_step_executions')
    op.drop_table('deployment_step_executions')
    op.drop_index('ix_resources_type', table_name='deployed_resources')
    op.drop_index('ix_resources_deployment', table_name='deployed_resources')
    op.drop_index(op.f('ix_deployed_resources_deployment_id'), table_name='deployed_resources')
    op.drop_table('deployed_resources')
    op.drop_index('ix_provisioned_dbs_type', table_name='provisioned_databases')
    op.drop_index('ix_provisioned_dbs_tenant', table_name='provisioned_databases')
    op.drop_index('ix_provisioned_dbs_app', table_name='provisioned_databases')
    op.drop_index(op.f('ix_provisioned_databases_tenant_id'), table_name='provisioned_databases')
    op.drop_index(op.f('ix_provisioned_databases_application_id'), table_name='provisioned_databases')
    op.drop_table('provisioned_databases')
    op.drop_index(op.f('ix_domains_tenant_id'), table_name='domains')
    op.drop_index('ix_domains_tenant', table_name='domains')
    op.drop_index(op.f('ix_domains_domain_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_application_id'), table_name='domains')
    op.drop_index('ix_domains_app', table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_deployments_tenant_id'), table_name='deployments')
    op.drop_index('ix_deployments_status', table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_at'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_application_id'), table_name='deployments')
    op.drop_index('ix_deployments_app_created', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('ix_applications_tenant_status', table_name='applications')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index('ix_applications_tenant_created', table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_nodes_type_status', table_name='infrastructure_nodes')
    op.drop_index('ix_nodes_status', table_name='infrastructure_nodes')
    op.drop_index('ix_nodes_heartbeat', table_name='infrastructure_nodes')
    op.drop_index(op.f('ix_infrastructure_nodes_status'), table_name='infrastructure_nodes')
    op.drop_index(op.f('ix_infrastructure_nodes_node_type'), table_name='infrastructure_nodes')
    op.drop_table('infrastructure_nodes')
    op.drop_index('ix_executions_tenant_state', table_name='executions')
    op.drop_index(op.f('ix_executions_tenant_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_state'), table_name='executions')
    op.drop_index(op.f('ix_executions_started_at'), table_name='executions')
    op.drop_index('ix_executions_recoverable_lookup', table_name='executions', postgresql_where=sa.text("state = 'STARTED'"))
    op.drop_index('ix_executions_queued_lookup', table_name='executions', postgresql_where=sa.text("state = 'QUEUED'"))
    op.drop_index(op.f('ix_executions_priority'), table_name='executions')
    op.drop_index(op.f('ix_executions_lease_owner'), table_name='executions')
    op.drop_index(op.f('ix_executions_lease_expires_at'), table_name='executions')
    op.drop_index(op.f('ix_executions_application_id'), table_name='executions')
    op.drop_index('ix_executions_app_state', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_templates_category', table_name='application_templates')
    op.drop_index('ix_templates_active', table_name='application_templates')
    op.drop_table('application_templates')
    # ### end Alembic commands ###
