"""add_health_tracking_to_deployed_resources

Revision ID: 616f14436ae6
Revises: d2c2a81eec13
Create Date: 2026-02-09 14:46:23.644896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616f14436ae6'
down_revision: Union[str, Sequence[str], None] = 'd2c2a81eec13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployed_resources', sa.Column('health_status', sa.Enum('UNKNOWN', 'HEALTHY', 'UNHEALTHY', 'STARTING', name='healthstatus'), nullable=False))
    op.add_column('deployed_resources', sa.Column('consecutive_health_failures', sa.Integer(), nullable=False))
    op.add_column('deployed_resources', sa.Column('last_health_check_at', sa.DateTime(), nullable=True))
    op.create_index('ix_resources_health', 'deployed_resources', ['health_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resources_health', table_name='deployed_resources')
    op.drop_column('deployed_resources', 'last_health_check_at')
    op.drop_column('deployed_resources', 'consecutive_health_failures')
    op.drop_column('deployed_resources', 'health_status')
    # ### end Alembic commands ###
